# Generated by Django 2.0.5 on 2018-05-25 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dealer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.TextField()),
                ('Place', models.TextField()),
                ('Email', models.TextField(null=True)),
                ('GST', models.TextField(null=True)),
                ('Phone', models.TextField(null=True)),
                ('Site_code', models.IntegerField()),
            ],
        ),
    ]
